### ISSUE TITLE
Null pointer deference results in segfault

### ISSUE THREAD

**Issue by ghost** [nwnlinux/nwmovies#2]
If anyone is still playing this -- lack of a .skip file for the videos will result in segfault.

http://home.ix.netcom.com/~jjingber/patch

**Comment by ghost** [comment]
Changed the the description to reflect local code.

**Comment by zzqzzqzzq** [comment]
Thank you.    I'll take a closer look and merge hopefully later today

**Comment by zzqzzqzzq** [comment]
Merged - Heh - kinda obvious when you look at it.   Sorry 'bout that - Thanks for the patch!
