### ISSUE TITLE
Rebuild new nwmovies.so

### ISSUE THREAD

**Issue by scfarley** [nwnlinux/nwmovies#4]
The .so is out of date in relation to the code.  Please rebuild it.  Making a release for it would be great for installations.  This would help my work on the FreeBSD port (https://svnweb.freebsd.org/ports/head/games/linux-nwnclient/) of the Linux binary.

Thank you.

**Comment by scfarley** [comment]
On a side note, I found mpv to work better on FreeBSD than ffplay.  ffplay does not go full screen for me.  This may be useful in the documentation for people that prefer mpv:

```sh
export NWMOVIES_PLAY_COMMAND="mpv --fullscreen --keep-open=no" \
        "--no-config --no-input-cursor --no-osc --no-terminal" \
        "--osd-level=0"
```

**Comment by zzqzzqzzq** [comment]
What flavor of Linux would you prefer it built on? 

I've got Fedora 26, CentOS6, and CentOS7 images handy. No Ubuntu.

But to be honest, I don't run the Linux version any longer, so I'm afraid you'll have to volunteer to test it. :)

**Comment by scfarley** [comment]
I did a test build with Ubuntu that worked, but a CentOS 7 image would be great as that is the base Linux used on FreeBSD.

I will gladly test it.  Woe is me to have to play^H^H^H^Htest a game.  ;)

Thank you very much for taking care of these issues!

Out of curiosity, what platform do you run these days?

**Comment by zzqzzqzzq** [comment]
Its been rebuilt on C7.   Give it a whirl..

I also updated the documentation, w your above comment, and repackaged everything.   

Desktops: Win7/Win10
Backend: ESX, w/ RHEL/CentOS, a little Fedora, and OpenVMS VM's running on top of it.

Mostly it boils down to gaming.  I do Linux "stuff" professionally, and while Linux has came along way, I don't really have the patience to fight with it in the evenings when all I want to do is relax, and play a game. 

I'll leave this issue open for while, till I hear back from you.

Thank you for the updates!

David

**Comment by scfarley** [comment]
I apologize for taking such a long time.  The binary does work.  You can close this.

However, I have a tiny patch for another change incoming in a PR.  :grin:

**Comment by zzqzzqzzq** [comment]
LOL  :-) - Consider it closed.
