### ISSUE TITLE
Newer distributions don't ship libelf.a (32bit)

### ISSUE THREAD

**Issue by Unaccounted4** [nwnlinux/nwmovies#6]
Howdy,

Spectacular work on this! It's been awesome to be able to keep playing the original version on Linux with working cutscenes.

With gamescope being ubiquitous these days, I found out you can make the BinkPlayer window look like it's a part of the same one as the game just by running all of it inside gamescope: 
```
cd "$(dirname "$0")"
export LD_PRELOAD=./nwmovies.so
export LD_LIBRARY_PATH=./miles:$LD_LIBRARY_PATH
export SDL_MOUSE_RELATIVE=1
gamescope -H 1080 -f -- ./nwmain $@
```
The problem came when I was trying to build nwmovies on Fedora 40 and it kept complaing it couldn't find -lelf despite elfutils-libelf-devel.i686 being installed. Some googling later, I found the last version of Fedora to ship libelf.a was Fedora 32, so I tracked down the package, extracted it, and made sure CPPFLAGS and LDFLAGS could see it. That made it work.

Is there a chance you could update nwmovies to use the new libelf.so?

**Comment by zzqzzqzzq** [comment]
I'll take a gander, but no guarantees... 

I have to upgrade my Fedora image from 39 to 40 (and its been going on a couple of hours now... )

**Comment by zzqzzqzzq** [comment]
The simple fix is to change the line that reads: (in nwmovies_install.pl)

`$command = sprintf("%s %s %s -Wall -shared -g -I/usr/include/libelf -I%s/libdis -o %s/nwmovies.so %s/nwmovies.c %s/nwmovies_lookup.c %s/nwmovies_cookie.c %s/nwmovies_player.c %s/nwmovies_link.S %s -ldl -Wl,-static -lelf -Wl,-Bdynamic", `

to 
`$command = sprintf("%s %s %s -Wall -shared -g -I/usr/include/libelf -I%s/libdis -o %s/nwmovies.so %s/nwmovies.c %s/nwmovies_lookup.c %s/nwmovies_cookie.c %s/nwmovies_player.c %s/nwmovies_link.S %s -ldl -lelf",`

Removing the two Wl options surrounding -lelf.  

That being said, I found a bug in the code, and wanted to shush the warnings up (one of which I don't understand), so a commit is going to take longer. 

I think I'll also modify the file layout somewhat so downloading is simply a "git clone https://github.com/nwnlinux/nwmovies", followed by nwmovies/nwmovies_install.pl build.

HTH, 

David

**Comment by Unaccounted4** [comment]
Awesome! Thank you so much. That workaround alone helps a bunch, already. 

Much appreciated
